FROM eclipse-temurin:21-jdk-jammy
#
## Establece el directorio de trabajo en la imagen
WORKDIR /app
#
COPY . /app
###RUN mvn clean clean
CMD ["java", "-jar", "target/spring-004-web-y-servicios-0.0.1-SNAPSHOT.jar"]
